//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SppLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SppLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap available_100x100 {
            get {
                object obj = ResourceManager.GetObject("available_100x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_stop_icon {
            get {
                object obj = ResourceManager.GetObject("Button-stop-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap configuration_1 {
            get {
                object obj = ResourceManager.GetObject("configuration 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Icon_32 {
            get {
                object obj = ResourceManager.GetObject("Export_Icon_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Final_splash_nelf {
            get {
                object obj = ResourceManager.GetObject("Final_splash_nelf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Final_splash_nelf1 {
            get {
                object obj = ResourceManager.GetObject("Final_splash_nelf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Final_splash_panda2 {
            get {
                object obj = ResourceManager.GetObject("Final_splash_panda2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart_icon {
            get {
                object obj = ResourceManager.GetObject("heart-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hu {
            get {
                object obj = ResourceManager.GetObject("hu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_gear {
            get {
                object obj = ResourceManager.GetObject("icon_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import_Icon_32 {
            get {
                object obj = ResourceManager.GetObject("Import_Icon_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information_icon {
            get {
                object obj = ResourceManager.GetObject("Information_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing.
        /// </summary>
        internal static string Launcher_bwExport_DoWork_Compressing {
            get {
                return ResourceManager.GetString("Launcher_bwExport_DoWork_Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Accounts.
        /// </summary>
        internal static string Launcher_bwExport_DoWork_Export_Accounts {
            get {
                return ResourceManager.GetString("Launcher_bwExport_DoWork_Export_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Completed.
        /// </summary>
        internal static string Launcher_bwExport_RunWorkerCompleted_Export_Completed {
            get {
                return ResourceManager.GetString("Launcher_bwExport_RunWorkerCompleted_Export_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Accounts.
        /// </summary>
        internal static string Launcher_bwImport_DoWork_Import_Accounts {
            get {
                return ResourceManager.GetString("Launcher_bwImport_DoWork_Import_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Completed.
        /// </summary>
        internal static string Launcher_bwImport_RunWorkerCompleted_Import_Completed {
            get {
                return ResourceManager.GetString("Launcher_bwImport_RunWorkerCompleted_Import_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Launcher_bwUpdate_DoWork_ERROR {
            get {
                return ResourceManager.GetString("Launcher_bwUpdate_DoWork_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Server Update Available.
        /// </summary>
        internal static string Launcher_bwUpdate_DoWork_New_Server_Update_Available {
            get {
                return ResourceManager.GetString("Launcher_bwUpdate_DoWork_New_Server_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        internal static string Launcher_bwUpdate_DoWork_New_Version {
            get {
                return ResourceManager.GetString("Launcher_bwUpdate_DoWork_New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available: V.
        /// </summary>
        internal static string Launcher_bwUpdate_DoWork_New_Version_Available__V {
            get {
                return ResourceManager.GetString("Launcher_bwUpdate_DoWork_New_Version_Available__V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to download?.
        /// </summary>
        internal static string Launcher_bwUpdate_DoWork_You_want_to_download_ {
            get {
                return ResourceManager.GetString("Launcher_bwUpdate_DoWork_You_want_to_download_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        internal static string Launcher_bwUpdate_RunWorkerCompleted_Up_to_date {
            get {
                return ResourceManager.GetString("Launcher_bwUpdate_RunWorkerCompleted_Up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Update.
        /// </summary>
        internal static string Launcher_Checking_Update {
            get {
                return ResourceManager.GetString("Launcher_Checking_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangosd Crashed.
        /// </summary>
        internal static string Launcher_CheckMangosCrashed_Tick_Mangosd_Crashed {
            get {
                return ResourceManager.GetString("Launcher_CheckMangosCrashed_Tick_Mangosd_Crashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is automatically restart..
        /// </summary>
        internal static string Launcher_CheckMangosCrashed_Tick_The_process_is_automatically_restart_ {
            get {
                return ResourceManager.GetString("Launcher_CheckMangosCrashed_Tick_The_process_is_automatically_restart_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to start World of Warcraft?.
        /// </summary>
        internal static string Launcher_CheckWowRun_Tick_Would_you_like_to_start_World_of_Warcraft_ {
            get {
                return ResourceManager.GetString("Launcher_CheckWowRun_Tick_Would_you_like_to_start_World_of_Warcraft_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Exception: CloseProcess
        ///.
        /// </summary>
        internal static string Launcher_CloseProcess_ {
            get {
                return ResourceManager.GetString("Launcher_CloseProcess_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Shutdown.
        /// </summary>
        internal static string Launcher_CloseProcess_Login_Shutdown {
            get {
                return ResourceManager.GetString("Launcher_CloseProcess_Login_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Shutdown.
        /// </summary>
        internal static string Launcher_CloseProcess_World_Shutdown {
            get {
                return ResourceManager.GetString("Launcher_CloseProcess_World_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take effect when you restart Launcher..
        /// </summary>
        internal static string Launcher_englishToolStripMenuItem_Click_Changes_will_take_effect_when_you_restart_Launcher_ {
            get {
                return ResourceManager.GetString("Launcher_englishToolStripMenuItem_Click_Changes_will_take_effect_when_you_restart" +
                        "_Launcher_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Launcher_export_Backup {
            get {
                return ResourceManager.GetString("Launcher_export_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Characters.
        /// </summary>
        internal static string Launcher_export_Export_Characters {
            get {
                return ResourceManager.GetString("Launcher_export_Export_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Characters.
        /// </summary>
        internal static string Launcher_export_Exporting_Characters {
            get {
                return ResourceManager.GetString("Launcher_export_Exporting_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress.
        /// </summary>
        internal static string Launcher_import_Decompress {
            get {
                return ResourceManager.GetString("Launcher_import_Decompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Characters.
        /// </summary>
        internal static string Launcher_import_Import_Characters {
            get {
                return ResourceManager.GetString("Launcher_import_Import_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Bots: N/A.
        /// </summary>
        internal static string Launcher_import_Online_Bots__N_A {
            get {
                return ResourceManager.GetString("Launcher_import_Online_Bots__N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Changed RealmList.wtf and after exit SPP change back original realmlist..
        /// </summary>
        internal static string Launcher_Launcher_Auto_Changed_RealmList_wtf_and_after_exit_SPP_change_back_original_realmlist_ {
            get {
                return ResourceManager.GetString("Launcher_Launcher_Auto_Changed_RealmList_wtf_and_after_exit_SPP_change_back_origi" +
                        "nal_realmlist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Launcher_magyarToolStripMenuItem_Click_1_Info {
            get {
                return ResourceManager.GetString("Launcher_magyarToolStripMenuItem_Click_1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update started.
        ///Do lag for several times..
        /// </summary>
        internal static string Launcher_RandomizeBotsMethod_ {
            get {
                return ResourceManager.GetString("Launcher_RandomizeBotsMethod_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Exception: RealmChange
        ///.
        /// </summary>
        internal static string Launcher_RealmChange_ {
            get {
                return ResourceManager.GetString("Launcher_RealmChange_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Exception: RealmWrite
        ///.
        /// </summary>
        internal static string Launcher_RealmChange0_ {
            get {
                return ResourceManager.GetString("Launcher_RealmChange0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Realm.
        /// </summary>
        internal static string Launcher_RealmdStart_Starting_Realm {
            get {
                return ResourceManager.GetString("Launcher_RealmdStart_Starting_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Exception: RealmRestore
        ///.
        /// </summary>
        internal static string Launcher_RealmRestore_ {
            get {
                return ResourceManager.GetString("Launcher_RealmRestore_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realmlist.
        /// </summary>
        internal static string Launcher_RealmRestore_Realmlist {
            get {
                return ResourceManager.GetString("Launcher_RealmRestore_Realmlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored.
        /// </summary>
        internal static string Launcher_RealmRestore_Restored {
            get {
                return ResourceManager.GetString("Launcher_RealmRestore_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is required for reset bots.
        ///Restart now?.
        /// </summary>
        internal static string Launcher_ResetBots_ {
            get {
                return ResourceManager.GetString("Launcher_ResetBots_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset bots.
        /// </summary>
        internal static string Launcher_rstchck_DoWork_Reset_bots {
            get {
                return ResourceManager.GetString("Launcher_rstchck_DoWork_Reset_bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangosd process is running.
        ///You want close the running process?.
        /// </summary>
        internal static string Launcher_SearchProcess_ {
            get {
                return ResourceManager.GetString("Launcher_SearchProcess_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Launcher_SearchProcess_Warning {
            get {
                return ResourceManager.GetString("Launcher_SearchProcess_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Exception: SearchProcess
        ///.
        /// </summary>
        internal static string Launcher_SearchProcess0_ {
            get {
                return ResourceManager.GetString("Launcher_SearchProcess0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mysqld process is running.
        ///You want close the running process?.
        /// </summary>
        internal static string Launcher_SearchProcess2_ {
            get {
                return ResourceManager.GetString("Launcher_SearchProcess2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to announce .
        /// </summary>
        internal static string Launcher_SrvAnnounce_Tick_announce_ {
            get {
                return ResourceManager.GetString("Launcher_SrvAnnounce_Tick_announce_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Mysql.
        /// </summary>
        internal static string Launcher_StartAll_Starting_Mysqlm {
            get {
                return ResourceManager.GetString("Launcher_StartAll_Starting_Mysqlm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is down.
        /// </summary>
        internal static string Launcher_startNStop_Derver_is_down {
            get {
                return ResourceManager.GetString("Launcher_startNStop_Derver_is_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online bot: N/A.
        /// </summary>
        internal static string Launcher_startNStop_Online_bot__N_A {
            get {
                return ResourceManager.GetString("Launcher_startNStop_Online_bot__N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Launcher_startNStop_Start {
            get {
                return ResourceManager.GetString("Launcher_startNStop_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Launcher_startNStop_Stop {
            get {
                return ResourceManager.GetString("Launcher_startNStop_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Launcher_tmrWorld_Tick_Online {
            get {
                return ResourceManager.GetString("Launcher_tmrWorld_Tick_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to play.
        /// </summary>
        internal static string Launcher_Traymsg_Ready_to_play {
            get {
                return ResourceManager.GetString("Launcher_Traymsg_Ready_to_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers Started.
        /// </summary>
        internal static string Launcher_Traymsg_Servers_Started {
            get {
                return ResourceManager.GetString("Launcher_Traymsg_Servers_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading World.
        /// </summary>
        internal static string Launcher_WorldStart_Loading_World {
            get {
                return ResourceManager.GetString("Launcher_WorldStart_Loading_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap not_available_100x100 {
            get {
                object obj = ResourceManager.GetObject("not-available_100x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Other_Power_Restart_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Other-Power-Restart-Metro-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Other_Power_Switch_User_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Other-Power-Switch-User-Metro-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paypal_donate_button {
            get {
                object obj = ResourceManager.GetObject("paypal_donate_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_paypal {
            get {
                object obj = ResourceManager.GetObject("pic_paypal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_tick {
            get {
                object obj = ResourceManager.GetObject("pic_tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Places_server_database_icon {
            get {
                object obj = ResourceManager.GetObject("Places-server-database-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play_1_Hot_icon {
            get {
                object obj = ResourceManager.GetObject("Play-1-Hot-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report_bug_icon {
            get {
                object obj = ResourceManager.GetObject("report-bug-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_animation {
            get {
                object obj = ResourceManager.GetObject("search_animation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap temporarily_not_available_100x100 {
            get {
                object obj = ResourceManager.GetObject("temporarily_not_available_100x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap us {
            get {
                object obj = ResourceManager.GetObject("us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Windows_Close_Program_icon {
            get {
                object obj = ResourceManager.GetObject("Windows-Close-Program-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap world_of_warcraft {
            get {
                object obj = ResourceManager.GetObject("world-of-warcraft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wow_cataclysm_icon_by_versewastaken_d30rcse {
            get {
                object obj = ResourceManager.GetObject("wow_cataclysm_icon_by_versewastaken-d30rcse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WoW_icon {
            get {
                object obj = ResourceManager.GetObject("WoW-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
